redbrick/nomad

ansible/templates/nomad-base.hcl.j2

Enable Telemetry with prometheus metrics so that Nomad metrics can be scraped and alerts can be created if there's an issue.

ansible/templates: Enable Nomad Telemetry

---

jobs/nginx/anime-manga-soc.hcl

the new image runs nginx so this is a simple change to point to 80 rather than 3000

prod yay :) git statusgit status

---

jobs/traefik.hcl
jobs/user-projects/general/nova-timetable.hcl

This file directory structure can also be used for 4th year projects (user-projects/(third/fourth)-year-project)
I can't validate this, but checkout this branch on one of the hosts and run `nomad job validate <path>` to ensure the config is okay, followed by `nomad job plan <path>` to plan it. Run the job at that point using the check-id. Once you're happy that it runs, return to the master branch and merge this PR.
nova@redbrick.dcu.ie requested this to be deployed.
A DNS entry will need to be made before planning to ensure that the cert can be generated by traefik.

Add job for a nova-timetable user project

---

jobs/user-projects/general/nova-timetable.hcl

This PR is done in coordination with https://github.com/novanai/timetable-sync/pull/1 to add redis to the nova-timetable job

Add redis task to nova-timetable job

---

jobs/dcusr.hcl

Adds the website for DCU Solar Racing
Site works fine for the moment however:
- currently hosted on a redbrick subdomain for testing
- some secrets have yet to be added (currently all necessary secrets are present but will need to add more once DCUSR make this public)*

add Solar Racing website

---

cluster-config/README.md
cluster-config/ingress-pool.hcl
jobs/games/gate-proxy.hcl
jobs/traefik.hcl

adds the `ingress` node pool, mainly for the bastion vm and adds it to the relevant jobs

add ingress node pool

---

jobs/nginx/11ty-website.hcl

adds the [11ty website](https://github.com/redbrick/11ty-website) and hosts it on canary.redbrick.dcu.ie

add 11ty-website

---

jobs/services/hedgedoc-backup.hcl
jobs/services/hedgedoc.hcl

A few notes for this one:
- this has been upgraded from `hackmdio/hackmd:1.3.0` on zeus
- currently running `hedgedoc/hedgedoc:1.6.0`
- Upgrading to hedgedoc >= 1.7.0 requires more migrations so this will be done to a later time
- this job is constrained to `chell`, this is because mounting a db to an NFS mount is extremely unwise. This will be revisited later with CSI
- `CMD_LDAP_USERNAMEFIELD` has been set meaning usernames are shown in the UI as opposed to uuid number
***Do not merge until I add the backup script!!!***

add hedgedoc job

---

jobs/services/postgres.hcl

Adds a postgresql job to be used by all redbrick internal services
Based off: https://git.dbyte.xyz/distro/nomad/src/branch/master/jobs/postgresql/postgresql.hcl 
Notes:
- currently constrained and mounted on `wheatley` until CSI is setup for database containers

add postgres job

---

jobs/services/vaultwarden.hcl

Once again mostly kanged from https://git.dbyte.xyz/distro/nomad/src/branch/master/jobs/vaultwarden.hcl
yubico and email are not configured and so are left commented out

add vaultwarden job

---

jobs/services/privatebin.hcl

Now that the [old pastebin is gone](https://github.com/redbrick/nix-configs/pull/117), we can point its domain to the new service

privatebin: add paste.redbrick

---

ansible/roles/configure-nfs-client/tasks/main.yml

mount nfs from icarus at `/oldstorage` for api and brickbot

ansible: mount oldstorage

---

jobs/services/wetty.hcl

adds `wetty` to aperture
This cannot be deployed yet as there is no route from the new network to either of the login boxes.

add wetty to aperture

---

jobs/user-vms/README.md
jobs/user-vms/bastion.hcl

configures the bastion-vm job to use a preconfigured image rather than a base debian image with cloudinit configs.
Tested: 27/01/2024

bastion-vm: use preconfigured image

---

jobs/services/api.hcl
jobs/services/brickbot.hcl

updates the perms of `ldap.secret` to a `chmod 600`
Prevents this warning:
```
Warning: Password file /etc/ldap.secret is publicly readable/writeable
```
Not too crucial but still better to follow best practices

update ldap secret perms

---

jobs/dcusr.hcl
jobs/nginx/ams-amikon.hcl
jobs/services/hedgedoc.hcl

traefik changed their host rules naming convention
Let's fix that!

jobs: update traefik rule for hosts following latest traefik standard

---

jobs/services/wetty.hcl

- sets the base bath of wetty to `/`
- adds all the current and legacy domains for wetty

wetty: set base path and add all the domains

---

jobs/services/members-mysql-backup.hcl
jobs/services/members-mysql.hcl

- adds `members-mysql` job file
- this is temporarily constrained to `wheatley` for performance and sanity (until CSI is finalised)
- adds a backup cron job to backup the db (based on the postgres backup job)

add members-mysql

---

jobs/user-projects/general/nova-timetable.hcl

Update the nomad job to support [timetable-sync v2.1.0](https://github.com/novanai/timetable-sync/releases/tag/v2.1.0). Not entirely sure it's correct but I followed the nomad docs so I hope it's okay!

Update nova timetable-sync job

---

jobs/user-projects/general/nova-timetable.hcl

Adds a postgres database to the nova-timetable job for the bot.
This will require the path for the bot token to be updated.

Add database to nova-timetable job

---

jobs/user-projects/general/nova-timetable.hcl

Adds support for the clubs & societies calendar.
Requires https://github.com/CheeseLad/clubsandsocs-api/pull/4 to be merged and released.

Add cns support to nova-timetable job

---

ansible/templates/nomad-client.hcl

Adds, hairpin mode to the the bridge network mode. This makes connecting different tasks on the same host much easier.
See here: https://developer.hashicorp.com/nomad/docs/configuration/client#bridge_network_hairpin_mode

ansible/nomad: enable bridge hairpin mode

---

jobs/socs/dcusr.hcl

Next_PUBLIC env variables are client side and in standalone instance this has to be passed during build time rather than runtime. so its not needed for the job

update env variables
